/** Server-owned export DTO. Never accept this snapshot from an HTTP request body. */
export interface ExportBinding {
  packageId: string;
  inputRevision: number;
  configVersion: string;
  modelVersion: string;
  selectionId: string;
  catalogVersion: string;
  engineVersion: string;
  rulesVersion: string;
  evidenceVersion: string;
  outputVersion: string;
}
export type ValueStatus = 'known' | 'unresolved' | 'unsupported';
export interface MaterialRow {
  id: string;
  description: string;
  quantity: number | null;
  unit: string;
  status: ValueStatus;
  subjectIds: string[];
  sourceIds: string[];
  unresolvedReason: string | null;
}
export interface CutRow {
  pieceId: string;
  segmentIds: string[];
  jointIds: string[];
  length: number | null;
  unit: string;
  status: ValueStatus;
  sourceIds: string[];
  unresolvedReason: string | null;
  /** Modeled centerline in the same unit; for a traced drawing, a plan projection. */
  centerline?: number | null;
}
export interface AssemblyStep {
  id: string;
  instruction: string;
  pieceIds: string[];
  jointIds: string[];
  sourceIds: string[];
  status: ValueStatus;
  unresolvedReason: string | null;
}
export interface InputFactRow {
  id: string; subjectIds: string[]; field: string; value: string | number | boolean | null; unit: string | null;
  confirmation: string; provenance: string; context: string; unknownReason: string | null;
  source: { description: string; assetId: string | null; page: number | null };
}
export interface PlanView {
  id: string;
  title: string;
  unit: string;
  segments: { sourceLabel?: string; id: string; pieceIds: string[]; from: [number, number, number]; to: [number, number, number] }[];
  joints: { id: string; position: [number, number, number] }[];
  context?: { sourceLabel?: string; id: string; kind: string; positions: [number, number, number][] }[];
}
export interface ChangeRow {
  id: string;
  kind: 'added' | 'removed' | 'retained' | 'proposed_reuse' | 'changed';
  entityType: 'material' | 'cut' | 'joint' | 'operation';
  subjectIds: string[];
  before: string | null;
  after: string | null;
  description: string;
  sourceIds: string[];
}
export interface ExportSnapshot {
  siteReview?: { alternatives?: Array<{label:string;metrics:string;cuts:string;binding:string}>; reason: string; evidence: Array<{label:string;page:number;synthetic:boolean;image?:string}>; readings: string[]; reviews: Array<{reviewer:string;decision:string;conditions:string;inputRevision:number;recordedAt:string;current:boolean;checks?:Array<{topic:string;answer:string;evidence:string}>}> };
  binding: ExportBinding;
  /** Binding on the stored derived outputs, not a copy generated by this exporter. */
  derivedBinding: ExportBinding;
  intent: 'prepare_from_drawing' | 'adapt_to_site';
  title: string;
  scope: string;
  drawingReference: string;
  inputFacts?: InputFactRow[];
  selectedPlan: PlanView;
  baselinePlan?: PlanView;
  materials: MaterialRow[];
  cuts: CutRow[];
  assembly: AssemblyStep[];
  changes: ChangeRow[];
  findings: { id: string; status: 'pass' | 'fail' | 'unknown' | 'not_applicable'; description: string; subjectIds: string[]; sourceIds: string[] }[];
  unresolvedItems: string[];
  sources: { id: string; title: string; reference: string }[];
  /** Saved inputs as entered, with their basis, so a test assumption is never read as a measurement. */
  inputs?: InputRow[];
  /** Entities outside the scope: shown for traceability, never part of the work or a purchase. */
  retainedContext?: { id: string; kind: string; label: string | null }[];
}
export interface InputRow {
  id: string;
  field: string;
  subjectIds: string[];
  value: string | number | boolean | null;
  unit: string | null;
  status: 'confirmed' | 'proposed' | 'unknown';
  basis: 'test_assumption' | 'sample' | 'recorded';
  source: string;
  evidenceAssetId: string | null;
}
export type ExportFileName = 'work-package.pdf' | 'bom.csv' | 'cut-list.csv' | 'manifest.json';
export interface ExportManifest {
  schemaVersion: 1;
  exportId: string;
  createdAt: string;
  binding: ExportBinding;
  snapshotHash: string;
  drawingReference?: string;
  inputFacts?: InputFactRow[];
  protectedContext?: PlanView["context"];
  draft: true;
  unresolvedCount: number;
  unresolvedItems: string[];
  files: { name: Exclude<ExportFileName, 'manifest.json'>; sha256: string; bytes: number; contentType: string }[];
}
export class ExportError extends Error {
  constructor(public status: 400 | 404 | 409 | 422, message: string) { super(message); }
}
