import { preparePdfExcerpts, excerptSections } from '../src/sources/pdf-excerpts.js';
import { afterEach, expect, it } from 'vitest';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { FieldService } from '../src/service.js';
import { SourceStore } from '../src/sources/store.js';
import { attachSourcePdf } from '../src/sources/pdf.js';
import { createApp } from '../src/api.js';
const cleanup: Array<() => void> = [];
afterEach(() => cleanup.splice(0).forEach(f => f()));
it('prepares real PDF pages and serves only authorized, bounded pages behind authentication', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'source-pdf-'));
  const service = new FieldService(dir);
  cleanup.push(() => { service.store.close(); rmSync(dir, { recursive: true, force: true }); });
  const sources = new SourceStore(service.store.db);
  sources.import({ id: 'manual', title: 'Fixture manual', publisher: 'Test', edition: 'A', type: 'manufacturer', scope: { productIds: ['fixture'] }, demonstration: false, authorization: { basis: 'Test fixture', storeAndIndex: true, useWithAi: true, display: 'full' }, filename: 'manual.md', content: '<!-- page: 1 -->\n## First page\nFixture source text.' });
  const bytes = readFileSync(join(import.meta.dirname, '../../../fixtures/uploads/native-text-manual.pdf'));
  const doc = await attachSourcePdf(sources, dir, 'manual', bytes);
  expect(doc.pdf?.sha256).toBe(createHash('sha256').update(bytes).digest('hex'));
  expect(readFileSync(join(dir, 'source-pdfs', doc.pdf!.sha256, 'original.pdf'))).toEqual(bytes);
  const app = createApp(service, { token: 'source-pdf-test-token', sources, sourceSearch: { select: async (_, passages) => passages.map(p => p.section.key) } });
  const headers = { Authorization: 'Bearer source-pdf-test-token' };
  const answer = await (await app.request('/api/rules/search', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ question: 'Fixture' }) })).json();
  expect(answer.sources[0].page.image).toBe('/api/sources/manual/pages/1');
  const path = answer.sources[0].page.image;
  expect((await app.request(path)).status).toBe(401);
  const page = await app.request(path, { headers });
  expect(page.status).toBe(200);
  expect(page.headers.get('Content-Type')).toBe('image/png');
  expect(Buffer.from(await page.arrayBuffer()).subarray(1, 4).toString()).toBe('PNG');
  for (const n of ['0', '1.5', '999', '01']) expect((await app.request(`/api/sources/manual/pages/${n}`, { headers })).status).toBe(404);
  const section = sources.sections(doc.id)[0];
  const excerpt = { id: 'fixture', sectionKey: section.key, page: 1, label: 'Fixture', text: section.text, box: { x: .1, y: .1, w: .8, h: .4 }, contextBox: { x: 0, y: 0, w: 1, h: 1 }, pageWidth: 600, pageHeight: 800 };
  expect(() => preparePdfExcerpts(sources, doc.id, { sha256: 'wrong', excerpts: [excerpt] })).toThrow(/hash/);
  expect(() => preparePdfExcerpts(sources, doc.id, { sha256: doc.pdf!.sha256, excerpts: [{ ...excerpt, text: 'Invented wording' }] })).toThrow(/verbatim/);
  expect(() => preparePdfExcerpts(sources, doc.id, { sha256: doc.pdf!.sha256, excerpts: [{ ...excerpt, contextBox: { x: 0, y: 0, w: .1, h: .1 } }] })).toThrow(/Context/);
  const prepared = preparePdfExcerpts(sources, doc.id, { sha256: doc.pdf!.sha256, excerpts: [excerpt] });
  expect(excerptSections(prepared, [section])[0].text).toBe(section.text);
  const result = await (await app.request('/api/rules/search', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ question: 'Fixture' }) })).json();
  const crop = result.sources.find((s: { excerpt?: unknown }) => s.excerpt);
  expect(crop.excerpt.box).toEqual(excerpt.box);
  const listing = await (await app.request('/api/sources', { headers })).json();
  expect(listing.documents[0].pdf).not.toHaveProperty('excerpts');
  const detail = await (await app.request('/api/sources/manual', { headers })).json();
  expect(detail.document.pdf).not.toHaveProperty('excerpts');
  expect((await app.request(crop.link, { headers })).status).toBe(200);
  expect(result.timings.compositionMs).toBe(0);
  sources.db.prepare('UPDATE source_documents SET data=? WHERE id=?').run(JSON.stringify({ ...doc, authorization: { ...doc.authorization, display: 'reference_only' } }), doc.id);
  expect((await app.request(path, { headers })).status).toBe(403);
  expect(excerptSections({ ...prepared, authorization: { ...prepared.authorization, display: 'excerpt' } }, [section])).toEqual([]);
  await expect(attachSourcePdf(sources, dir, 'manual', bytes)).rejects.toMatchObject({ code: 'display_limited' });
});
